ROOT = ..
BINS = ahw.exe testahw.exe
TESTS = testahw.exe
LIBS =  $(ROOT)/sspemdd/sspemdd.a $(ROOT)/alglib/alglib.a
ADDIT_INC = -I$(ROOT)/alglib -I$(ROOT)/sspemdd

include $(ROOT)/all.inc
-include deps.inc

