
ROOT = ..
OBJS = alglibinternal.o alglibmisc.o ap.o dataanalysis.o diffequations.o fasttransforms.o integration.o interpolation.o linalg.o optimization.o solvers.o specialfunctions.o statistics.o
LIBS = alglib.a



include $(ROOT)/all.inc
-include deps.inc